dependencies:
- name: postgresql
  version: 0.11.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: provisionDataStore.postgresql.enabled
- name: redis
  version: ~1.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: provisionDataStore.redis.enabled
