apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "discourse.fullname" . }}
  labels:
    app: {{ template "discourse.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  postgresql-host: {{ template "discourse.postgresql.fullname" . }}
  redis-host: {{ template "discourse.redis.fullname" . }}
{{ toYaml .Values.config | indent 2 }}